### ISSUE TITLE
SM breakpoint applied for all breakpoints

### ISSUE THREAD

**Issue by Awilum** [asmcss/assembler#16]
I can't understand why `sm|mb:2;` applied for all breakpoints? 
I should set `mb:0` for all other breakpoints to fix this behaviour?

This is not working
```html
<a x-style="sm|mb:2;" href="#">Link</a>
```

This is works 
```html
<a x-style="sm|mb:2; md|mb:0; lg|mb:0;" href="#">Link</a>
```

but it is overcomplicated to create responsive elements.

**Comment by sorinsarca** [comment]
This depends on your choosen [design mode](https://asmcss.com/docs/1.x/configuration.html#breakpoints):

- if "mobile first" (default) a breakpoint like md means md and up
- if "desktop first" a breakpoint like md means md and down

So, on your example you should probably use `mb: 2; md|mb: 0` - which means use margin-bottom 2 when < md and use margin-bottom 0 when >= md

I (personally) prefer the "desktop first" approach, because on mobile you usually hide stuff. If you start from mobile (mobile first) you have to think how it will look on desktop when you add stuff
